
server:
  port: 8082

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  docker:
    compose:
      enabled: false

  profiles:
    active: dev

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-token-expiration-time:  120000 # 2 minutes (in milliseconds) (900000 for 15 minutes)
    refresh-token-expiration-time: 604800000 # 7 days (in milliseconds)


spring.config.import: optional:file:.env[.properties]
